<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<form action="index.php" method="post">
    <input type="email" name="email">
    <input type="password" name="password">
        <button>submit</button>
</form>
    
</body>
</html>



<?php
     $email = $_POST['email'];
    $password = $_POST['password'];

    $conn = new mysqli('localhost','root','','test');
    echo "index.php";

    if($conn->connect_error){
        die('conection faild : ' .$conn->connect_error);
    }
    else{
        $stmt = $conn->prepare("insert into registration(email,password)values(?,?)");
        $stmt->bind_param("ss" , $email,$password);
        $stmt->execute();

        echo "registration Done";
        $stmt->close();
        $conn->close();
     }
    




// //The url you wish to send the POST request to
// $url = $file_name;

// //The data you want to send via POST
// $fields = [
//     'email'      => $state,
//     'password' => $valid,
//     'btnSubmit'         => 'Submit'
// ];

// //url-ify the data for the POST
// $fields_string = http_build_query($fields);

// //open connection
// $ch = curl_init();

// //set the url, number of POST vars, POST data
// curl_setopt($ch,CURLOPT_URL, $url);
// curl_setopt($ch,CURLOPT_POST, true);
// curl_setopt($ch,CURLOPT_POSTFIELDS, $fields_string);

// //So that curl_exec returns the contents of the cURL; rather than echoing it
// curl_setopt($ch,CURLOPT_RETURNTRANSFER, true); 

// //execute post
// $result = curl_exec($ch);
// echo $result;

?>